
server:
      port: 9082



eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance: localhost
      
      
spring:
   application:
      name: USER-SERVICE
      