
server:
      port: 9191



eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance: localhost
      
      
spring:
   application:
      name: API-GATEWAY
   cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
              - Path=/users/**
        filters:
          - name: CircuitBreaker
            args:
              name: USER-SERVICE
              fallbackuri: forward:/userServiceFallBack
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
             - Path=/departments/**
        filters:
            - name: CircuitBreaker
              args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/departmentServiceFallBack
              
hystrix:
       command:
             fallback:
                execution:
                      isolation:
                             thread:
                                timeoutInMilliseconds: 4000
                                
management:
        endpoints:
               web:
                 exposure:
                     include: hystrix-stream
      
